version: "3"

services:
  scoutsuite:
    image: opendevsecops/scoutsuite:latest
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    command:
      - "--provider=aws" 
    volumes:
      - ./reports:/session